#!/bin/bash

date 
echo "CI: $CI"
echo "CIRLECI: $CIRLECI"
echo "CIRCLE_ARTIFACTS: $CIRCLE_ARTIFACTS"
echo "CIRCLE_BRANCH: $CIRCLE_BRANCH"
echo "CIRCLE_BUILD_NUM: $CIRCLE_BUILD_NUM"
echo "CIRCLE_COMPARE_URL: $CIRCLE_COMPARE_URL"
echo "CIRCLE_NODE_INDEX: $CIRCLE_NODE_INDEX"
echo "CIRCLE_NODE_TOTAL: $CIRCLE_NODE_TOTAL"
echo "CIRCLE_PREVIOUS_BUILD_NUM: $CIRCLE_PREVIOUS_BUILD_NUM"
echo "CIRCLE_PROJECT_REPONAME: $CIRCLE_PROJECT_REPONAME"
echo "CIRCLE_PROJECT_USENAME: $CIRCLE_PROJECT_USENAME"
echo "CIRCLE_SHA1: $CIRCLE_SHA1"
echo "CIRCLE_USERNAME: $CIRCLE_USERNAME"
echo "CI_TEST_REPOSTS: $CI_TEST_REPOSTS"
echo "CI_PULL_REQUEST: $CI_PULL_REQUEST"
echo "CI_PULL_REQUESTS: $CI_PULL_REQUESTS"

echo "node-ver: $(node -v)"
echo "npm-ver: $(npm -v)"

echo "foo: $foo"
echo "baz: $baz"
